apiVersion: polyfea.github.io/v1alpha1
kind: MicroFrontend
metadata:
  name: xdt-ambulance-ufe
spec:
  frontendClass: md-shell # default obsiahnutý v základe polyfea md-shell
  service:
    name: xdt-ambulance-ufe # referencia na službu odkiaľ sa má načítať modul
  modulePath: build/ambulance-ufe.esm.js # cesta v rámci služby kde sa modul nachádza