apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xdt-ambulance-ufe-content
spec:
  microFrontend: xdt-ambulance-ufe
  element: xdt-ambulance-wl-app
  attributes:
    - name: base-path
      value: ./xdt-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xdt-ambulance-wl(/.*)?$"