apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xdt-ambulance-ufe-content
spec:
  microFrontend: xdt-ambulance-ufe
  element: truhlar-ambulance-we-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xdt-ambulance-wl(/.*)?$"